# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Papaya standalone deployment

on:
  push:
    branches: [ ci-cd-actions ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from Github branch
      uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and test
      run: |
        # Step 1: setup directories and files as super user
        # Step 2: create a non-super user for elastic to run
        id -u build &>/dev/null || useradd --user-group --create-home --shell /bin/bash build
        su build -c "bash ./gradlew clean"

        # Step 3: Fix environment specific variables
        # sed -i "s/#build_version#/${BUILD_NUMBER}/g" server/src/main/java/com/titaniamlabs/service/CryptoService.java

        # Step 4: Run the build
        su build -c "bash ./gradlew build"

    